config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :clients
  root :to => 'clients#index'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :client
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many  :accounts , dependent: :destroy,foreign_key: "client_id"
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all.page(params[:page]).per(10)
    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Busquedas >>>>>>>>>>>>>>>>>>>>>>>>>>
    if params[:search].present?
      @busqueda = params[:search].rstrip
      puts @busqueda
      consulta = "(accountnumber LIKE :datos )"
      @accounts = Account.select("accounts.*").where(consulta, datos: "%#{@busqueda}%").order('created_at DESC').page(params[:page]).per(10)
      if @accounts.empty?
        @error = 1
      end
    end

    if params[:idClien].present? && !params[:search].present?
      @accounts = Account.where("client_id=?",params[:idClien]).page(params[:page]).per(10)
    elsif params[:idClien].present? && params[:search].present?
      @accounts = Account.where("client_id=? = #{params[:idClien]} AND  #{@consulta}").page(params[:page]).per(10)

    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
    @edit = true
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.js
      format.json { head :locale }
    end
    @accounts =Account.all.page(params[:page]).per(10)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:accountnumber, :belongto, :client_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.page(params[:page]).per(10)

    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Busquedas >>>>>>>>>>>>>>>>>>>>>>>>>>
    if params[:search].present?
      @busqueda = params[:search].rstrip
      puts @busqueda
      consulta = "(clients.name LIKE :datos OR clients.lastname LIKE :datos OR lastnamem LIKE :datos )"
      @clients = Client.select("clients.*").where(consulta, datos: "%#{@busqueda}%").order('created_at DESC').page(params[:page]).per(10)
      if @clients.empty?
        @error = 1
      end
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'El cliente fue creado con éxito.' }
        format.json { render :show, status: :created, location: @client }
        format.js
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'El cliente fue actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.js
      format.json { head :locale }
    end
    @clients =Client.all.page(params[:page]).per(10)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def client_params
    params.require(:client).permit(:name, :lastname, :lastnamem, :age, :phone, :street, :colony, :housenumber, :town)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/accounts/_accountabla.html.erb
<%# <%********************* Sweetalert No Results *************************** %>
<% if @error.present? %>
  <script>
      swal({
          title: "Advertencia", text: "No se encontraron resultados", type: "warning"
      });
  </script>
<% end %>
<%# <%********************** Paginacion & Boton Crear *******************************%>
<div class="row">
  <div class="col-xs-12 col-md-4">
    <%= link_to '<span class="fa fa-cc-mastercard "></span> '.html_safe + 'Nuevo', new_account_path, :class => 'btn btn-primary btn-xs btx' %>
  </div>
  <div class="col-xs-12 col-md-8 form-group" align="right">
    <div class="detall_right">
      <% if @accounts.length == 1 %>
        <%= page_entries_info @accounts, entry_name: "Cuenta" %>
      <% else %>
        <%= page_entries_info @accounts, entry_name: "Cuentas".pluralize() %>
      <% end %>
    </div>
    <div class="pag_right">
      <%= paginate @accounts, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true %>
    </div>
  </div>
</div>

<%# <%********************** Tabla Clientes *******************************%>
<div id="tabla_cuentas" style="overflow: auto;">
  <table class="table footable no-paging">
    <thead>
    <tr>
      <th class="text-left" data-sort-ignore="true">Numero cuenta</th>
      <th class="text-center" data-sort-ignore="true">Pertenece a</th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Mostrar</th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Editar</th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Eliminar</th>
    </tr>
    </thead>

    <tbody>
    <% @accounts.each do |account| %>
      <tr id="account_<%= account.id %>">
        <td class="text-left" data-sort-ignore="true">
          ************<%= account.accountnumber.last(4) %>
        </td>
        <td class="text-center" data-sort-ignore="true">
          <%= account.client.name%><%= account.client.lastname%>  <%=account.client.lastnamem%>
        </td>
        <td class="text-center"><%= link_to '<i class="fa fa-file-text"></i>'.html_safe, account, class: "btn btn-xs btn-primary btx", :data => {toggle: "tooltip"}, title: "Mostrar" %></td>
        <td class="text-center"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_account_path(account), class: "btn btn-xs btn-warning btx", :data => {toggle: "tooltip"}, title: "Editar" %></td>
        <td class="text-center">
          <input type="hidden" value="<%= account.accountnumber.last(4) %>" id="account<%= account.id %>">
          <button class="btn btn-danger btn-xs  accounts" type="button" id="<%= account.id %>" data-toggle="tooltip" title="Eliminar">
            <i class="fa fa-trash-o"></i>
          </button>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%# <%********************** Paginacion & Boton Crear *******************************%>
<div class="row">
  <div class="col-xs-12 col-md-4">
    <%= link_to '<span class="fa fa-cc-mastercard "></span> '.html_safe + 'Nuevo', new_account_path, :class => 'btn btn-primary btn-xs btx' %>
  </div>
  <div class="col-xs-12 col-md-8 form-group" align="right">
    <div class="detall_right">
      <% if @accounts.length == 1 %>
        <%= page_entries_info @accounts, entry_name: "Cuenta" %>
      <% else %>
        <%= page_entries_info @accounts, entry_name: "Cuentas".pluralize() %>
      <% end %>
    </div>
    <div class="pag_right">
      <%= paginate @accounts, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true %>
    </div>
  </div>
</div>




app/views/accounts/_form.html.erb
<% if @error.present? %>
  <script>
      swal({
          title: "Advertencia", text: "No se encontraron resultados", type: "warning"
      });
  </script>
<% end %>
<%= form_for @account , :html => {:id => 'form1'} do |f| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> al guardar la cuenta:</h2>
      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><% message %> Tienes que elegir un cliente </li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-2 col-lg-2"></div>
    <div class="col-xs-6 col-lg-7">
      <div class="row">
        <div class="col-xs-12">
          <div class="field">
            <p class="text-center">
              <label>Número de Cuenta</label>
                <%= f.text_field :accountnumber , id: "numcta",class: 'form-control', autocomplete: 'off',placeholder: " ************1234",  :maxlength => 16%>
              <small id="labnumcta" style="display: none;">.</small>
            </p>
          </div>
        </div>

        <% if @edit == true %>
          <div class="col-xs-12">
            <div class="field">
              <p class="text-center">
              <center>
                <label>Pertenece a</label>
                <div>
                  <input type="hidden" value="<%= @account.client_id%>" id="cliente<%= @account.id %>">
                  <label ><%=  @account.client.name%> <%=  @account.client.lastname%> <%=  @account.client.lastnamem%> </label>
                </div>
              </center>
              </p>
            </div>
          </div>
          </div>
        <%else %>
          <div class="col-xs-12">
            <div class="field">
              <p class="text-center">
              <center>
                <label>Pertenece a</label>
                <%= f.select(:client_id, Client.all.collect {|u| [u.name + ' ' + u.lastname+' '+u.lastnamem, u.id]},  {class: 'form-control',  :prompt => 'Selecciona un cliente' }, {:class => "form-control"},  ) %>
              </center>
              <small id="labbelong" style="display: none;">.</small>
              </p>
            </div>
          </div>
          </div>
        <%end %>




      <div class="col-xs-12 hr-line-dashed"></div>
      <div class="col-xs-12">
        <div class="actions">
          <button type="submit" , class="btn btn-xs btn-primary " , value=" Guardar" , name="btnSave">
            <i class="fa fa-user">Guardar</i>
          </button>
          <%= link_to '<span class="fa fa-user" ></span>  '.html_safe + " Cancelar", accounts_path, :class => 'btn btn-xs btn-warning btx' %>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/accounts/destroy.js.erb
$('#account:<%= @account.id %>').remove();
$("#accountabla").html("<%= escape_javascript(render("accountabla")) %>");

app/views/accounts/edit.html.erb
<div class="block-area wrapper wrapper-content animated fadeInRight" id="responsiveTable">
  <div class="row">
    <div class="col-md-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h1>Editar Cuenta</h1>
        </div>
        <div class="ibox-content">
          <%= render 'form', account: @account %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/index.js.erb
$("#accountabla").html("<%= escape_javascript(render("accountabla")) %>");
$('table').footable({paginate: false});
if ($(window).width() <= 425) {
  var hlp = document.getElementById('ayuda')
  hlp.parentNode.removeChild(hlp);
  document.getElementById('btnrt').innerHTML="<i class='fa fa-search'></i>"
  document.getElementById('searchbar').style.padding = "0px"
  var x = document.getElementsByClassName("btx");
  var i;
  for (i = 0; i < x.length; i++) {
     x[i].classList.remove('btn-xs');
     x[i].classList.add('btn-block');
   }
}

app/views/accounts/new.html.erb
<div class="block-area wrapper wrapper-content animated fadeInRight" id="responsiveTable">
  <div class="row">
    <div class="col-md-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h1>Nueva Cuenta</h1>
        </div>
        <div class="ibox-content">
          <%= render 'form', account: @account %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="block-area wrapper wrapper-content animated fadeInRight" id="responsiveTable">
  <div class="row">
    <div class="col-md-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h1>Mostrar Cuenta</h1>
          <div class="ibox-content" id="responsiveTable">
            <div class="row">
              <div class="col-xs-1"></div>
              <div class="col-xs-10 text-left">
                <div class="ibox" style="border:1px solid #E7EAEC">
                  <div class="ibox-title" style="color: #2F4050">

                  </div>
                  <div class="ibox-content" style="display: block;">
                    <table class="footable table table-stripped toggle-arrow-tiny">
                      <tbody>
                      <tr>
                        <td><strong>Número de Cuenta:</strong></td>
                        <td>  ************<%= @account.accountnumber.last(4) %></td>
                      </tr>

                      <tr>
                        <td> <strong>Pertenece a:</strong></td>
                        <td><%= @account.client.name%><%= @account.client.lastname%>  <%=@account.client.lastnamem%>  </td>
                      </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              <div class="col-xs-1"></div>
            </div>
            <div class="row">
              <div class="col-md-4">
                <%= link_to '<i class="span class="fa fa-cc-mastercard"></i> '.html_safe + "Volver",  accounts_path, :class => 'btn btn-xs btn-primary bx' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/_clientetabla.html.erb
<%# <%********************* Sweetalert No Results *************************** %>
<% if @error.present? %>
  <script>
      swal({title: "Advertencia", text: "No se encontraron resultados", type: "warning"});
  </script>
<% end %>
<%# <%********************** Paginacion & Boton Crear *******************************%>
<div class="row">
  <div class="col-xs-12 col-md-4">
    <%= link_to '<span class="fa fa-user"></span> '.html_safe + 'Nuevo', new_client_path, :class => 'btn btn-primary btn-xs btx' %>
  </div>
  <div class="col-xs-12 col-md-8 form-group" align="right">
    <div class="detall_right">
      <% if @clients.length == 1 %>
        <%= page_entries_info @clients, entry_name: "Cliente" %>
      <% else %>
        <%= page_entries_info @clients, entry_name: "Cliente".pluralize() %>
      <% end %>
    </div>
    <div class="pag_right">
      <%= paginate @clients, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true %>
    </div>
  </div>
</div>

<%# <%********************** Tabla Clientes *******************************%>
<div id="tabla_clientes" style="overflow: auto;">
  <table class="table footable no-paging">
    <thead>
    <tr>
      <th class="text-left" data-sort-ignore="true">Nombre</th>
      <th class="text-center" data-sort-ignore="true">Apellido paterno</th>
      <th class="text-center" data-sort-ignore="true">Apellido materno</th>
      <td class="text-center" data-sort-ignore="true">Cuentas</td>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Mostrar</th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Editar</th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Eliminar</th>
    </tr>
    </thead>

    <tbody>
    <% @clients.each do |client| %>
      <tr id="client_<%= client.id %>">
        <td class="text-left"><%= client.name %></td>
        <td class="text-center"><%= client.lastname %></td>
        <td class="text-center"><%= client.lastnamem %></td>
        <td class="text-center">
          <%# if client.accounts.present? %>
            <% if client.accounts.count > 0 %>
              <%= client.accounts.count %>|
              <%= link_to '<button class="btn btn-primary btn-xs accounts" data-toggle="tooltip" type="button"><i class="fa fa-file-text"></i></button>'.html_safe, {:controller => "accounts", :action => "index", :idClien => client.id}, :data => {:no_turbolink => true} %>
            <% else %>
              <%= client.accounts.count %>|
              <%= link_to '<button type="button" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i></button>'.html_safe, new_account_path(:id => client.id) %>
            <% end %>
          <%# else %>
<!--            <%#= client.accounts.count %>|-->
            <%#= link_to '<button type="button" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i></button>'.html_safe, new_account_path(:id => client.id) %>
          <%# end %>
        </td>
        <td class="text-center"><%= link_to '<i class="fa fa-file-text"></i>'.html_safe, client, class: "btn btn-xs btn-primary btx", :data => {toggle: "tooltip"}, title: "Mostrar" %></td>
        <td class="text-center"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_client_path(client), class: "btn btn-xs btn-warning btx", :data => {toggle: "tooltip"}, title: "Editar" %></td>
        <td class="text-center">
          <input type="hidden" value="<%= client.name %>" id="client<%= client.id %>">
          <button class="btn btn-danger btn-xs  clients" type="button" id="<%= client.id %>" data-toggle="tooltip" title="Eliminar">
            <i class="fa fa-trash-o"></i>
          </button>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%# <%********************** Tabla Clientes *******************************%>
<%# <%********************** Paginacion & Boton Crear *******************************%>
<div class="row">
  <div class="col-xs-12 col-md-4">
    <%= link_to '<span class="fa fa-user"></span> '.html_safe + 'Nuevo', new_client_path, :class => 'btn btn-primary btn-xs btx' %>
  </div>
  <div class="col-xs-12 col-md-8 form-group" align="right">
    <div class="detall_right">
      <% if @clients.length == 1 %>
        <%= page_entries_info @clients, entry_name: "Cliente" %>
      <% else %>
        <%= page_entries_info @clients, entry_name: "Cliente".pluralize() %>
      <% end %>
    </div>
    <div class="pag_right">
      <%= paginate @clients, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true %>
    </div>
  </div>
</div>

app/views/clients/_form.html.erb
<%= form_for @client, :html => {:id => 'form1'} do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> al guardar el cliente:</h2>
      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-2 col-lg-2"></div>
    <div class="col-xs-6 col-lg-7">
      <div class="row">
        <div class="col-xs-6">
          <div class="field">
            <p class="text-center">
              <label>Nombre</label>
              <%= f.text_field :name, class: 'form-control', autocomplete: 'off', placeholder: " Nombre", id: "name", :maxlength => 100%>
              <small id="labname" style="display: none;">.</small>
            </p>
          </div>
        </div>

        <div class="col-xs-6">
          <div class="field">
            <p class="text-center">
              <label>Apellido Paterno</label>
              <%= f.text_field :lastname, class: 'form-control', autocomplete: 'off', placeholder: " Apellido Paterno", id: "ap", :maxlength => 100 %>
              <small id="labap" style="display: none;">.</small>
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-6">
          <div class="field">
            <p class="text-center">
              <label>Apellido Materno</label>
              <%= f.text_field :lastnamem, class: 'form-control', autocomplete: 'off', placeholder: " Apellido Materno", :id => "am", :maxlength => 100%>
              <small id="labam" style="display: none;">.</small>
            </p>
          </div>
        </div>


        <div class="col-xs-6">
          <div class="form-group" id="data_1">
            <p class="text-center">
              <label> Edad</label>
            <div class="input-group  datepicker" data-autoclose="true" data-placement="left">
              <span class="input-group-addon"><i class="fa fa-calendar" id="cumple"></i></span>
              <%= f.text_field :age, class: "form-control bir onlynumbers", :placeholder => 'DD/MM/YYYY', :id => 'birthday',  :autocomplete => :off %>
            </div>
            <small id="labbirthday" style="display: none;">.</small>
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-6">
          <div class="field">
            <div align="center" class="form-group">
              <label>Teléfono</label>
              <%= f.text_field :phone, class: 'form-control', autocomplete: 'off', placeholder: 'Teléfono', id: 'phon',  maxlength:  10 %>
              <small id="labphon" style="display: none;">.</small>
            </div>
          </div>
        </div>
      </div>

      <fieldset>
        <legend>Dirección</legend>
        <div class="row">
          <div class="col-xs-6">
            <div class="field">
              <div align="center" class="form-group">
                <label>Calle</label>
                <%= f.text_field :street, class: 'form-control', autocomplete: 'off', placeholder: " Calle", :id => "add", :maxlength => 50 %>
                <small id="labadd" style="display: none;">.</small>
              </div>
            </div>
          </div>


          <div class="col-xs-6">
            <div class="field">
              <div align="center" class="form-group">
                <label>Colonia</label>
                <%= f.text_field :colony, class: 'form-control', autocomplete: 'off', placeholder: " Colonia", :id => "col", :maxlength => 50 %>
                <small id="labcol" style="display: none;">.</small>
              </div>
            </div>
          </div>
        </div>


        <div class="row">
          <div class="col-xs-6">
            <div class="field">
              <div align="center" class="form-group">
                <label>Número de Casa</label>
                <%= f.text_field :housenumber, class: 'form-control', autocomplete: 'off', placeholder: " Número de Casa", :id => "casa", :maxlength => 3%>
                <small id="labcasa" style="display: none;">.</small>
              </div>
            </div>
          </div>


          <div class="col-xs-6">
            <div class="field">
              <div align="center" class="form-group">
                <label>Municipio</label>
                <%= f.text_field :town, class: 'form-control', autocomplete: 'off', placeholder: " Municipio", :id => "mun", :maxlength => 50 %>
                <small id="labmun" style="display: none;">.</small>
              </div>
            </div>
          </div>


        </div>
      </fieldset>
    </div>
    <div class="col-xs-12 hr-line-dashed"></div>
    <div class="col-xs-12">
      <div class="actions">
        <button type="submit" , class="btn btn-xs btn-primary btx" , value=" Guardar" , name="btnSave">
          <span class="fa fa-user"> Guardar</span>
        </button>
        <%= link_to '<span class="fa fa-user" ></span>  '.html_safe + " Cancelar", clients_path, :class => 'btn btn-xs btn-warning btx' %>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
    $(document).ready(function () {
        $('table').footable({paginate: false});
    });

    // $('#bir .input-group.date').datepicker({
    //     todayBtn: "linked",
    //     keyboardNavigation: false,
    //     forceParse: false,
    //     calendarWeeks: true,
    //     autoclose: true
    // });
</script>

app/views/clients/destroy.js.erb
$('#client_<%= @client.id %>').remove();
$("#clientetabla").html("<%= escape_javascript(render("clientetabla")) %>");

app/views/clients/edit.html.erb
<div class="block-area wrapper wrapper-content animated fadeInRight" id="responsiveTable">
  <div class="row">
    <div class="col-md-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h1>Editar Cliente</h1>
        </div>
        <div class="ibox-content">
          <%= render 'form', client: @client %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<div class="block-area wrapper wrapper-content animated fadeInRight" id="responsiveTable">
  <div class="row">
    <div class="col-md-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h1>Mostrar Cliente</h1>
          <div class="ibox-content" id="responsiveTable">
            <div class="row">
              <div class="col-xs-1"></div>
              <div class="col-xs-10 text-left">
                <div class="ibox" style="border:1px solid #E7EAEC">
                  <div class="ibox-title" style="color: #2F4050">

                  </div>
                  <div class="ibox-content" style="display: block;">
                    <table class="footable table table-stripped toggle-arrow-tiny">
                      <tbody>
                      <tr>
                        <td><strong>Nombre:</strong></td>
                        <td>
                        <%= @client.name %>
                        </td>
                      </tr>
                      <tr>
                        <td> <strong>Apellido Paterno:</strong></td>
                        <td> <%= @client.lastname %></td>
                      </tr>

                      <tr>
                        <td><strong>Apellido Materno:</strong></td>
                        <td><%= @client.lastnamem %></td>
                      </tr>

                      <tr>
                        <td><strong>Edad:</strong></td>
                        <td><%= @client.age %></td>
                      </tr>

                      <tr>
                        <td><strong>Teléfono:</strong></td>
                        <td><%= @client.phone %></td>
                      </tr>

                      <tr>
                        <td><strong>Calle:</strong></td>
                        <td> <%= @client.street %></td>


                      </tr>

                      <tr>
                        <td> <strong>Colonia:</strong></td>
                        <td><%= @client.colony %></td>
                      </tr>

                      <tr>
                        <td><strong>Número Casa:</strong></td>
                        <td><%= @client.housenumber %></td>
                      </tr>

                      <tr>
                        <td> <strong>Municipio:</strong></td>
                        <td><%= @client.town %></td>
                      </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              <div class="col-xs-1"></div>
            </div>
            <div class="row">
              <div class="col-md-4">
                <%= link_to '<i class="span class="fa fa-user"></i> '.html_safe + "Volver", clients_path, :class => 'btn btn-xs btn-primary' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="text-center">
      KS Soluciones S.A. de C.V. &copy; 1998-<%= Time.now.year %>
    </div>

</div>